version: '3'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: central_relacionamento
      MYSQL_ROOT_PASSWORD: "password"
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
